security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true

    enable_authenticator_manager: true

    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'email'

    role_hierarchy:
        ROLE_ADMIN: 'ROLE_USER'

    firewalls:
        api_token:
            pattern: ^api/token$
            security: false
        api:
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # Token
        #        - { path: '^/api/token', methods: [ 'POST' ], roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }

        # Other
#        - { path: '^/api', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
